#include "arduino_secrets.h"
/* 
  Sketch generated by the Arduino IoT Cloud Thing "Nodemcu"
  https://create.arduino.cc/cloud/things/00bb3fdd-8d53-40da-9454-f0decc5eae46 

  Arduino IoT Cloud Variables description

  The following variables are automatically generated and updated when changes are made to the Thing

  bool light;
  bool ota;

  Variables which are marked as READ/WRITE in the Cloud Thing will also have functions
  which are called when their values are changed from the Dashboard.
  These functions are generated with the Thing and added at the end of this sketch.
*/

#include "thingProperties.h"
#include <ESP8266WiFi.h>
#include <ESP8266httpUpdate.h>

#define LED_PIN LED_BUILTIN  // Built-in LED


void setup() {
  // Initialize serial and wait for port to open:
  Serial.begin(9600);
  // This delay gives the chance to wait for a Serial Monitor without blocking if none is found
  delay(1500); 

  // Defined in thingProperties.h
  initProperties();

  // Connect to Arduino IoT Cloud
  ArduinoCloud.begin(ArduinoIoTPreferredConnection);
  
  /*
     The following function allows you to obtain more information
     related to the state of network and IoT Cloud connection and errors
     the higher number the more granular information you’ll get.
     The default is 0 (only errors).
     Maximum is 4
 */
  setDebugMessageLevel(2);
  ArduinoCloud.printDebugInfo();
   pinMode(LED_PIN, OUTPUT);
  digitalWrite(LED_PIN, HIGH); // LED OFF initially
}

void loop() {
  ArduinoCloud.update();
  // Your code here 
  
  
}

/*
  Since Light is READ_WRITE variable, onLightChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onLightChange()  {
  // Add your code here to act upon Light change
  digitalWrite(LED_PIN, light ? LOW : HIGH); // LOW = ON, HIGH = OFF
  Serial.print("LED is now ");
  Serial.println(light ? "ON" : "OFF");
}

/*
  Since Ota is READ_WRITE variable, onOtaChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onOtaChange() {
  if (ota) {
    Serial.println("Starting OTA update...");

    WiFiClient client;
    t_httpUpdate_return ret = ESPhttpUpdate.update(
      client,
      "https://raw.githubusercontent.com/divyagoldenaxe-ctrl/esp8266-firmware1/main/bin.ino.nodemcu.bin"
    );

    switch (ret) {
      case HTTP_UPDATE_OK:
        Serial.println("Update successful, rebooting...");
        break;

      case HTTP_UPDATE_FAILED:
        Serial.printf("Update failed! Error: %s\n", ESPhttpUpdate.getLastErrorString().c_str());
        break;

      case HTTP_UPDATE_NO_UPDATES:
        Serial.println("No update available.");
        break;
    }

    ota = false;  // Reset toggle
  }
}
